### ISSUE TITLE
Expand Equipment section of character sheet.

### ISSUE THREAD

**Issue by SkriptKitty** [pullmangames/pullmangames.github.io#16] opened 2015-11-13 05:16 UTC
_I'm mostly just trying this out as a way to capture some "to do" list items or things that I think would be cool to add...._

Eventually we should make it possible to add stuff to the Equipment section.

**Comment by pullmangames** [comment] 2015-11-28 23:50
Duplicate of more detailed issue

**Closed as completed** 2015-11-28 23:49 UTC
Labels: DUPLICATE, enhancement, ship management, player tools, GM tools
